releases:
  - name: wordpress-stack
    namespace: wordpress
    chart: ./helm-charts/wordpress-stack
    values:
      - ./enviroments-config/staging.yaml
  
  - name: monitoring-stack
    namespace: monitoring
    chart: ./apps/monitoring
    values:
      - apps/monitoring/values.yaml
  
  - name: github-runner
    namespace: github-actions
    chart: ./github-actions/runner