repositories:
  - name: bitmami
    url: https://charts.bitnami.com/bitnami
  - name: longhorn          
    url: https://charts.longhorn.io
  - name: traefik
    url: https://traefik.github.io/charts
  - name: ingress-nginx
    url: https://kubernetes.github.io/ingress-nginx
  - name: metallb
    url: https://metallb.github.io/metallb
  - name: prometheus-community
    url: https://prometheus-community.github.io/helm-charts

helmDefaults:
  skipSchemaValidation: false
  wait: true
  timeout: 600
  waitForJobs: true
  historyMax: 10
  createNamespace: true

releases:     
  # - name: wordpress-stack
  #   needs:
  #     - longhorn-system/longhorn
  #     - networking/networking-stack
  #   namespace: wordpress-dev01
  #   chart: ../helm-charts/wordpress-stack
  #   values:
  #     - ./values/dev01/values.yaml
  #     - ./values/wordpress-stack-secrets.yaml.gotmpl
  
  # - name: wordpress-stack
  #   needs:
  #     - longhorn-system/longhorn
  #     - networking/networking-stack
  #   namespace: wordpress-prod01
  #   chart: ../helm-charts/wordpress-stack
  #   values:
  #     - ./values/prod01/values.yaml
  #     - ./values/wordpress-stack-secrets.yaml.gotmpl

  #Monitoring stack (kube-prometheus)
  # - name: monitoring-metric-stack
  #   needs:
  #     - networking/networking-stack
  #   namespace: monitoring
  #   chart: ../helm-charts/monitoring-stack/monitoring-metric-stack
  #   values:
  #     - ../helm-charts/monitoring-stack/monitoring-metric-stack/values.yaml

  #Tools stack (adminer for mysql, redis-insight for redis)
  # - name: monitoring-tools-stack
  #   needs:
  #     - networking/networking-stack
  #   namespace: monitoring
  #   chart: ../helm-charts/monitoring-stack/monitoring-tools-stack
  #   values:
  #     - ../helm-charts/monitoring-stack/monitoring-tools-stack/values.yaml
  # https://artifacthub.io/packages/helm/ectobit/adminer

  #could combine to 1 release later

  # - name: minio
  #   namespace: minio
  #   chart: ../helm-charts/minio-s3
  #   values:
  #     - ./values/minio-values.yaml.gotmpl

  #CSI storage drivers
  - name: longhorn
    namespace: longhorn-system
    chart: ../helm-charts/longhorn
    values:
      - ./values/longhorn-values.yaml

  # - name: networking-stack #First rollout
  #   namespace: networking
  #   chart: ../helm-charts/networking-stack
  #   values:
  #     - ../helm-charts/networking-stack/values.yaml
  
  # Certmanager for TLS certs
  # - name: cert-manager
  #   needs:
  #     - networking/networking-stack
  #   namespace: cert-manager
  #   chart: ../helm-charts/cert-manager
  #   values:
  #     - ../helm-charts/cert-manager/values.yaml