releases:
  # - name: wordpress-stack
  #   namespace: wordpress
  #   chart: ./helm-charts/wordpress-stack
  #   values:
  #     - ./enviroments-config/staging.yaml

  #CSI storage drivers
  - name: longhorn
    namespace: longhorn-system
    chart: ../helm-charts/longhorn
    values:
      - ../helm-charts/longhorn/values.yaml

  - name: networking-stack
    namespace: networking
    chart: ../helm-charts/networking-stack
    values:
      - ../helm-charts/networking-stack/values.yaml

  #Monitoring stack kube-prometheus-stack
  # - name: monitoring-stack
  #   namespace: monitoring
  #   chart: ../helm-charts/monitoring-stack
  #   values:
  #     - ../helm-charts/monitoring-stack/values.yaml