apiVersion: v1
kind: PersistentVolume
metadata:
  name: nginx-manager-data-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data/nginx-proxy-manager
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nginx-manager-letsencrypt-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data/nginx-letsencrypt
