apiVersion: v2
name: oauth2-proxy
description: A Helm chart for oauth2-proxy
home: https://oauth2-proxy.github.io/oauth2-proxy/
type: application
version: 0.1.0
dependencies:
  - name: oauth2-proxy
    version: 8.5.1
    repository: file://./dependencies/oauth2-proxy